import type { Metadata } from "next";
import { Inter, Cousine } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const cousine = Cousine({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-cousine",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cousine.className}>{children}</body>
    </html>
  );
}
